Zmzpwyb 34
miedzinski195659/zwinne-wks pull request #18
Opened 2018-04-03 12:45 UTC by krysiak195634

2018-04-04 08:49 UTC, lmiedzinski requested changes
Dodawanie nie odświeża listy.... Do poprawy pomimo oddania 2 dni po terminie

2018-04-04 09:01 UTC, krysiak195634 commented
Po dodaniu jest wywołana metoda wyświetlająca wszystkie role. Powinno działać i nie wiem dlaczego nie działa.

2018-04-05 15:59 UTC, krysiak195634 commented
Naprawiono błąd przy dodawaniu nowego stanowiska. Teraz lista stanowisk odświeża się przy każdym nowym dodanym stanowisku.

2018-04-05 19:19 UTC, lmiedzinski approved these changes
Wreszcie względnie ok

2018-04-05 19:19 UTC, merged