[ZMZPWYB-53] [ZMZPWYB-54] Rozwiązywanie testu
miedzinski195659/zwinne-wks pull request #38
Opened 2018-04-22 15:34 UTC by MaciejZakrzewski

2018-04-22 21:39 UTC, nullJaX requested changes
Proszę:
1. Dodać alert dotyczący walidacji wprowadzanych danych
2. Wyczyścić listę odpowiedzi przy nieprawidłowym wysyłaniu (tak, aby po ostatecznym wysłaniu nie było w bazie listy z 1000 elementów-odpowiedzi)
3. Dodać komunikat (albo zablokować przycisk "Resolve") o braku możliwości rozwiązania testu, ze względu na jego wcześniejszą ewaluację

2018-04-22 21:41 UTC, nullJaX commented on wks-recruiter/src/main/java/pl/lodz/p/it/wks/wksrecruiter/controllers/TestController.java
> +            return ResponseEntity.status(HttpStatus.CONFLICT).body(e.toString());
Leci 409, ale użytkownik nie wie co się dzieje w konsoli

2018-04-25 20:30 UTC, nullJaX commented
1. Przycisk "Resolve test" nadal jest widoczny po rozwiązaniu testu (lista testów) i nadal jest klikalny
2. Rozwiązując test drugi raz (bo "Resolve test" jest klikalny) wyrzucany jest 409 w konsoli bez komunikatu/alertu na froncie

2018-04-25 21:08 UTC, lmiedzinski requested changes
Koniecznie proszę zablokować ponowne rozwiązywanie testu

2018-04-26 19:35 UTC, lmiedzinski approved these changes

2018-04-26 19:37 UTC, nullJaX approved these changes

2018-04-26 19:37 UTC, merged