ZMZPWYB-64
miedzinski195659/zwinne-wks pull request #44
Opened 2018-05-11 18:05 UTC by DropsOnly

2018-05-11 23:26 UTC, nullJaX commented
Proszę o:
1. rozwiązanie konfliktów
2. zablokowanie przycisku "Evaluate answers" jeśli już próba została oceniona (nieaktualne jeśli edytor wg założeń może zmieniać swoją ocenę)
3. zmienić fragment kodu (plik **TestServiceImpl.java**):
`return testsRepository.findAll().stream().filter(test -> test.getAuthor().getName().equals(authentication.getName())).collect(Collectors.toList());`

na:

`return testsRepository.findAll().stream().filter(test -> test.getAuthor().getLogin().equals(authentication.getName())).collect(Collectors.toList());`

Uniemożliwia to przeglądanie testów w panelu Edytora (bo authentication.getName() zwraca de facto login, a nie imię użytkownika)

2018-05-11 23:28 UTC, nullJaX requested changes
W poprzednim komentarzu znajdują się zastrzeżenia.

2018-05-12 05:57 UTC, DropsOnly commented
1. Konflikty zostały rozwiązane.
2. Nieaktualne, edytor może zmienić potem swoją ocenę.
3. Metoda filtrowania została zmieniona.

Testowałeś wysyłanie notyfikacji?

2018-05-12 10:52 UTC, nullJaX commented
pinknie działa 👍 🥇

2018-05-12 10:52 UTC, nullJaX approved these changes

2018-05-12 10:53 UTC, merged