Zmzpwyb 70
miedzinski195659/zwinne-wks pull request #50
Opened 2018-05-17 13:11 UTC by krysiak195634

Proszę o sprawdzenie i wskazanie rzeczy do poprawy jeśli takowe będą.

2018-05-17 19:51 UTC, DropsOnly submitted a review, later dismissed

2018-05-17 19:51 UTC, DropsOnly commented on wks-recruiter-interface/src/app/layout/tests/tests-list/tests-list.component.html
> +              <div class="no-tests-message" *ngIf="testAttempts.length === 0">There are no test attempts available</div>
Ten napis się pojawi w pierwszej kolumnie tabeli. Powinno być pod całą tabelą i lepiej użyć np. h3 zamiast diva z customową klasą. Zdecydowanie ładniej to będzie wyglądało.

2018-05-17 19:51 UTC, DropsOnly commented on wks-recruiter-interface/src/app/layout/tests/tests-results/tests-results.component.html
> +              <tr *ngFor="let answer of testAttempt.answers; let i = index;">
A co w przypadku gdy w teście nie będzie pytań?

2018-05-17 19:51 UTC, DropsOnly commented on wks-recruiter-interface/src/app/layout/tests/tests-list/tests-list.component.scss
> +.results-card {
To nie jest potrzebne. W bootstrapie masz klasy takie jak mx-y, gdzie x to miejsce, w którym ma być margines a y to rozmiar marginesu. Poczytaj dokumentację. (np. mt-2 - margines top o wielkości 2).

2018-05-17 19:51 UTC, DropsOnly commented on wks-recruiter-interface/src/app/layout/tests/tests-list/tests-list.component.html
> +                <td class="col-9">{{testAttempt.test.name}}</td>
Tutaj kolumny nie dodają się do 12 a angular ma w sobie taki system, że dzieli widok na max 12 kolumn. Druga sprawa, po co to? Nie ma jakiejś klasy `table-responsive`? Jeśli coś zajmuje za dużo miejsca dodaj tooltipy jak w poprzednim zadaniu.

2018-05-18 12:47 UTC, nullJaX reviewed
Czemu wyświetlają się wszystkie podejścia użytkownika, nawet te nieocenione?
https://atlas.it.p.lodz.pl/jira/browse/ZMZPWYB-15

2018-05-18 12:47 UTC, nullJaX commented on wks-recruiter-interface/src/app/layout/tests/tests-results/tests-results.component.html
> +              <tr *ngFor="let answer of testAttempt.answers; let i = index;">
*bump*

2018-05-18 12:47 UTC, nullJaX commented on wks-recruiter-interface/src/app/layout/tests/tests-results/tests-results.component.html
> +              <tr *ngFor="let answer of testAttempt.answers; let i = index;">
To stanie się coś takiego, ja bym troszku czcionkę zmniejszył.
![image](https://user-images.githubusercontent.com/19861372/40234899-be0f9e2e-5aa8-11e8-8bf0-e679ae787422.png)

2018-05-18 12:47 UTC, nullJaX commented on wks-recruiter-interface/src/app/layout/tests/tests-results/tests-results.component.html
> +  <h4 class="modal-title">Test results</h4>
Proszę dodać nazwę testu w nagłówku modala.

2018-05-18 12:47 UTC, nullJaX commented on wks-recruiter-interface/src/app/layout/tests/tests-results/tests-results.component.html
> +                <td>{{ answer.answers }}</td>
W przypadku listy wielokrotnego wyboru proszę o rozdzielenie zaznaczonych odpowiedzi sekwencją znaków ", " (ze spacją), a nie "," (sam przecinek)

2018-05-18 12:50 UTC, nullJaX requested changes
Małe poprawki potrzebne.

2018-05-21 07:12 UTC, nullJaX requested changes
Jak w komentarzu.

2018-05-21 07:12 UTC, nullJaX commented on wks-recruiter-interface/src/app/layout/tests/tests-results/tests-results.component.html
> +          <h5 *ngIf="!resolved">This test has not been resolved yet.</h5>
nie **resolved**, tylko **evaluated**

2018-05-21 08:30 UTC, nullJaX approved these changes

2018-05-21 08:31 UTC, merged